# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Satoryu's Website
title_separator: "-"
name: Tatsuya Sato
description: Website about Tatsuya Sato
email: satoryu.1981@gmail.com
logo: assets/img/logo.png
google_analytics: UA-10079057-16
repository: satoryu/satoryu.com
timezone: Asia/Tokyo

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.satoryu.com" # the base hostname & protocol for your site

## For SEO tags plugin
author:
  name: Tatsuya Sato
  avatar: assets/img/profile.jpeg
  bio: Passionate Programmer / Father for two kids / MOSH'SH MATE
  location: Tokyo, Japan
  email: satoryu.1981@gmail.com
  links: &social-links
    - label: GitHub
      icon: fab fa-github-square
      url: https://github.com/satoryu
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/satoryu/
    - label: "Twitter"
      icon: fab fa-twitter-square
      url: https://twitter.com/satoryuofficial
    - label: Facebook
      icon: fab fa-facebook-square
      url: https://www.facebook.com/satoryu
    - label: Blog
      icon: fas fa-blog
      url: /blog/

footer:
  links: *social-links

search: true
google:
  search_engine_id: 014230504068243774542:crkzkwew2vw

# Social Sharing
og_image: /assets/img/ogp.png
twitter:
  username: satoryuofficial
social:
  type: Person
  name: Tatsuya Sato
  links:
    - https://twitter.com/satoryuofficial
    - https://www.facebook.com/satoryu
    - https://www.linkedin.com/in/satoryu/
    - https://www.instagram.com/satoryu/
    - https://github.com/satoryu
    - https://speakerdeck.com/satoryu

analytics:
  provider: google-gtag
  google:
    tracking_id: UA-10079057-16

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-linkpreview
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jemoji

# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt

include:
  - _pages

exclude:
  - api/
  - node_modules/
  - Gemfile*
  - package*.json

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      header:
        teaser: /assets/img/james-harrison-vpOeXr5wmR4-unsplash.jpeg
        overlay_image: /assets/img/james-harrison-vpOeXr5wmR4-unsplash.jpeg
        overlay_filter: 0.7
        caption: Photo by [James Harrison](https://unsplash.com/@jstrippa?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/programming?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
